### ISSUE TITLE
Add package to Pypi

### ISSUE THREAD

**Issue by lvieirajr** [arngarden/MongoDBProxy#19]
It would be great if this package could be added to Pypi.
So that we could install it with `pip install mongodbproxy` or something similar.

**Comment by big-kahuna-burger** [comment]
there is such package, just do ```pip install mongodbproxy```

**Comment by lvieirajr** [comment]
Yes, there is now because I uploaded it to PyPI since it looks like this package hasn't been maintained in a while.
